name: compile

on: [push, workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-24.04
    steps:
    - name: Setup Noto & Pandoc & ghostscript & ImageMagick
      uses: daaku/gh-action-apt-install@v4
      with:
        packages: fonts-noto-cjk pandoc ghostscript imagemagick
    - name: Setup TeXLive
      uses: teatimeguest/setup-texlive-action@v3
      with:
        version: 2023
        packages: |
          scheme-basic
          graphicx
          hyperref
          multicol
          anysize
          fontspec
          ctex
          tabularx
          chinese-jfm
          tex-gyre-bonum
          fandol
          url
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile
      run:  |
        # sudo mkdir /usr/share/ghostscript/9.55.0/iccprofiles
        # sudo cp ./icc/* /usr/share/ghostscript/9.55.0/iccprofiles/
        # sudo cp ./icc/* /usr/share/color/icc/ghostscript/
        sudo cp ./policy/policy.xml /etc/ImageMagick-6/policy.xml
        lualatex -interaction=nonstopmode -jobname=latest --output-directory=pdfs '000.tex'
        convert -density 300 ./pdfs/latest.pdf -append ./imgs/latest.png
        echo '/^\\begin{document}/ {print; found=1; next} found && /^% HEAD END/ {print "\\title{南哪消息' $(TZ=Asia/Urumqi date "+%F") '}\\maketitle"; print; found=0; next} found {next} {gsub(/section/, "subsection"); gsub(/\\centerline{\\huge/, "\\section{"); gsub(/\\begin{multicols}\{2\}/, ""); gsub(/\\end{multicols}/, ""); print; }' > pat
        awk -f pat 000.tex > tmp.tex
        pandoc tmp.tex -s -o ./html/latest.md
        pandoc --toc ./html/latest.md -s -o ./html/latest.html
        rm ./html/latest.md
        # tail ./html/latest.html -n +2 > ./README.md
        cp ./html/latest.html ./README.md
        rm tmp.tex ./pdfs/latest.out ./pdfs/latest.log ./pdfs/latest.aux
        dtm=$(TZ=Asia/Urumqi date '+%F')
        cp ./pdfs/latest.pdf ./pdfs/$dtm.pdf
        cp ./imgs/latest.png ./imgs/$dtm.png
        cp ./html/latest.html ./html/$dtm.html
    - name: Pushback
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "compile docs"
        git push
