name: compile

on: [push, workflow_dispatch]

jobs: 
  compile_pdf_html_md_rss:
    runs-on: ubuntu-24.04
    steps:
    - name: Setup Noto & Pandoc & beautifulsoup
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: fonts-noto-cjk pandoc python3-bs4
    - name: Setup TeXLive
      uses: teatimeguest/setup-texlive-action@v3
      with:
        version: 2023
        packages: |
          scheme-basic
          graphicx
          hyperref
          multicol
          anysize
          fontspec
          ctex
          tabularx
          chinese-jfm
          tex-gyre-bonum
          fandol
          url
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run:  bash ./compile_docs.sh
    - name: Pushback
      run: bash ./pushback.sh
  
  compile_image:
    needs: compile_pdf_html_md
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Gohstscript
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: ghostscript
    - name: Compile
      run:  |
        git pull
        dtm=$(TZ=Asia/Urumqi date '+%F')
        sudo cp ./policy/policy.xml /etc/ImageMagick-6/policy.xml
        convert -density 300 ./pdfs/latest.pdf -append ./imgs/latest.png
        cp ./imgs/latest.png ./imgs/$dtm.png
    - name: Pushback
      run: bash ./pushback.sh
