name: compile

on: [push, workflow_dispatch]

jobs: 
  compile_pdf_html_md:
    runs-on: ubuntu-24.04
    steps:
    - name: Setup Noto & Pandoc
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: fonts-noto-cjk pandoc
    - name: Setup TeXLive
      uses: teatimeguest/setup-texlive-action@v3
      with:
        version: 2023
        packages: |
          scheme-basic
          graphicx
          hyperref
          multicol
          anysize
          fontspec
          ctex
          tabularx
          chinese-jfm
          tex-gyre-bonum
          fandol
          url
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run:  |
        # sudo apt-get install -y imagemagick # cannot cahced
        # sudo mkdir /usr/share/ghostscript/9.55.0/iccprofiles
        # sudo cp ./icc/* /usr/share/ghostscript/9.55.0/iccprofiles/
        # sudo cp ./icc/* /usr/share/color/icc/ghostscript/
        # sudo cp ./policy/policy.xml /etc/ImageMagick-6/policy.xml
        lualatex -interaction=nonstopmode -jobname=latest --output-directory=pdfs '000.tex'
        # convert -density 300 ./pdfs/latest.pdf -append ./imgs/latest.png
        echo '/^\\begin{document}/ {print; found=1; next} found && /^% HEAD END/ {print "\\title{南哪消息' $(TZ=Asia/Urumqi date "+%F") '}\\maketitle"; print; found=0; next} found {next} {gsub(/section/, "subsection"); gsub(/\\centerline{\\huge/, "\\section{"); gsub(/\\begin{multicols}\{2\}/, ""); gsub(/\\end{multicols}/, ""); print; }' > pat
        awk -f pat 000.tex > tmp.tex
        cat header <(echo '<style>#textbox {display: flex;justify-content: space-between;}</style><div id="textbox"><p class="alignleft"><a href="https://nik-nul.github.io/news/"><svg fill="#0645ad" height="20px" width="20px" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 469.411 469.411" xml:space="preserve"><g><g><path d="M397.305,207.826c-67.733-59.947-161.493-61.12-194.56-59.307V74.706c0-5.867-4.8-10.667-10.667-10.667c-2.453,0-4.907,0.853-6.827,2.453L3.918,215.826c-4.587,3.733-5.227,10.453-1.493,15.04c0.427,0.533,0.96,0.96,1.493,1.493l181.333,149.333c4.587,3.733,11.307,3.093,15.04-1.493c1.6-1.92,2.453-4.267,2.453-6.827v-77.013c34.667-8,175.147-30.507,246.613,103.36c1.813,3.52,5.44,5.653,9.387,5.653c3.413,0,6.72-1.6,8.853-4.693c1.28-1.813,1.813-4.053,1.813-6.293C469.305,312.999,445.091,250.279,397.305,207.826z M260.558,269.159c-41.067,0-70.72,8.427-71.467,8.64c-4.587,1.28-7.68,5.44-7.68,10.24v62.72l-153.92-126.72l153.92-126.72v62.72c0,5.867,4.8,10.667,10.667,10.667c0.427,0,0.853,0,1.28-0.107c1.173-0.107,115.2-12.907,189.76,53.227c35.2,31.147,56.213,75.2,62.72,130.987C391.758,284.306,315.811,269.159,260.558,269.159z"/></g></g></svg></a></p><p class="aligncenter">订阅群：<a href="https://qm.qq.com/q/FGX1VYCrGS">962626571</a></p><p class="alignright"><i>Last Update: ' $(TZ=Asia/Shanghai LC_TIME=C date) '</i></p></div><div style="clear: both;"></div>') > h
        pandoc tmp.tex -s -o ./html/latest.md
        pandoc --toc ./html/latest.md -s -V colorlinks=true -V linkcolor=blue -V urlcolor=red -V toccolor=gray --css pandoc.css -H h --embed-resources -o ./html/latest.html
        pandoc ./html/latest.html --to 'markdown_strict+pipe_tables' -o ./README.md
        # cp ./html/latest.html ./README.md
        # tail ./html/latest.html -n +2 > ./README.md
        # cp ./html/latest.html ./README.md
        rm ./html/latest.md tmp.tex ./pdfs/latest.out ./pdfs/latest.log ./pdfs/latest.aux ./h
        dtm=$(TZ=Asia/Urumqi date '+%F')
        cp ./pdfs/latest.pdf ./pdfs/$dtm.pdf
        # cp ./imgs/latest.png ./imgs/$dtm.png
        cp ./html/latest.html ./html/$dtm.html
    - name: Pushback
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "compile docs"
        git push
  
  compile_image:
    needs: compile_pdf_html_md
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Gohstscript
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: ghostscript
    - name: Compile
      run:  |
        git pull
        dtm=$(TZ=Asia/Urumqi date '+%F')
        sudo cp ./policy/policy.xml /etc/ImageMagick-6/policy.xml
        convert -density 300 ./pdfs/latest.pdf -append ./imgs/latest.png
        cp ./imgs/latest.png ./imgs/$dtm.png
    - name: Pushback
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "compile img"
        git push
