name: initial

on: 
  workflow_dispatch:

jobs:
  mkdir:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: makedir
      run: |
        mkdir -p pdfs
    - name: pushback
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "mkdir"
        git push
