name: mail

on:
  workflow_dispatch:

jobs: 
  mail-test:
    runs-on: ubuntu-24.04
    steps:
    - name: Setup Pandoc
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: pandoc
    - name: Checkout
      uses: actions/checkout@v4

    - name: Send
      run:  |
        bash ./mail_prepare.sh
        python3 ./mail.py
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        MAILING_LIST: ${{ secrets.MAILING_LIST }}
