name: mail

on:
  workflow_dispatch:

jobs: 
  mail:
    runs-on: ubuntu-24.04
    steps:
    - name: Setup Pandoc
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: pandoc
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup bs4
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Send
      run:  |
        bash ./mail_prepare.sh
        python3 ./mail.py
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        MAILING_LIST: ${{ secrets.MAILING_LIST }}
